behaviors:
  DynamicHallwayFire:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory: 
        sequence_length: 64  
        memory_size: 256  
        use_recurrent: true
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.9
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 128  
      gail:
        gamma: 0.99
        strength: 0.05
        learning_rate: 0.0003
        demo_path: Demos/SingleModel.demo
        use_vail: true
    behavioral_cloning:
      demo_path: Demos/SingleModel.demo
      strength: 0.05
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
# environment_parameters:
#   room_count:
#     curriculum:
#       - name: Lesson0 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.1
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 2
#             max_value: 2
#       - name: Lesson1 # This is the start of the second lesson
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.3
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 3
#             max_value: 3
#       - name: Lesson2
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.5
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 4
#             max_value: 4
#       - name: Lesson3
#         value: 5