behaviors:
  TwoRoomFire:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.7
        demo_path: Demos/TwoRoomAgent.demo  # Updated demo path with GAIL
    behavioral_cloning:
      demo_path: Demos/TwoRoomAgent.demo  # Updated demo path
      strength: 0.7
      steps: 100000
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 20000
    threaded: true
  ThreeRoomFire:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory: 
        sequence_length: 64  
        memory_size: 256  
        use_recurrent: true
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 128
      gail:
        gamma: 0.99
        strength: 0.7
        demo_path: Demos/ThreeRoomAgent.demo  # Keep this demo path
    behavioral_cloning:
      demo_path: Demos/ThreeRoomAgent.demo  # Keep this demo path
      strength: 0.7
      steps: 100000
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
  FourRoomFire:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory: 
        sequence_length: 64  
        memory_size: 256  
        use_recurrent: true
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 128
      gail:
        gamma: 0.99
        strength: 0.7
        demo_path: Demos/FourRoomAgent.demo
    behavioral_cloning:
      demo_path: Demos/FourRoomAgent.demo
      strength: 0.7
      steps: 100000
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
  FiveRoomFire:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory: 
        sequence_length: 64  
        memory_size: 256  
        use_recurrent: true
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 128
      gail:
        gamma: 0.99
        strength: 0.7
        demo_path: Demos/FiveRoomAgent.demo
    behavioral_cloning:
      demo_path: Demos/FiveRoomAgent.demo
      strength: 0.7
      steps: 100000
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
