behaviors:
  DynamicHallwayFireCollabIL:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 128
      beta: 0.01
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      num_epoch: 3
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 512
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: Demos/SingleModelCollab.demo
        use_vail: false
    behavioral_cloning:
      demo_path: Demos/SingleModelCollab.demo
      strength: 0.5
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
# environment_parameters:
#   room_count:
#     curriculum:
#       - name: Lesson0 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.1
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 2
#             max_value: 2
#       - name: Lesson1 # This is the start of the second lesson
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.3
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 3
#             max_value: 3
#       - name: Lesson2
#         completion_criteria:
#           measure: progress
#           behavior: DynamicHallwayFire
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 0.5
#         value:
#           sampler_type: uniform
#           sampler_parameters:
#             min_value: 4
#             max_value: 4
#       - name: Lesson3
#         value: 5