behaviors:
  RobotReacher:
    trainer_type: ppo
    hyperparameters:
        batch_size: 64
        buffer_size: 1024
        learning_rate: 0.0003
        beta: 0.001
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
    network_settings:
        normalize: false
        hidden_units: 128
        num_layers: 3
        vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
        gail:
            strength: 0.9
            demo_path: Demos/Lite6Demo_3.demo
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    behavioral_cloning:
        demo_path: Demos/Lite6Demo_3.demo
        strength: 0.9
